# model_dir_path_relatevi_from_xml_dir            : "../models/ycb"            # to be changed for your env!
dir_path_relative_to_cwd : "./models/ycb" # to be changed for your env!
suffix_fname             : "clouds/merged_cloud.ply"
